function NLX_viewEvents(NEV,TimeValue)

TSmin = min(NEV.TimeStamps);
TSmax = max(NEV.TimeStamps);
ViewRange = 60000;

if nargin<2
    figure
    axes( ...
        'units','normalized', ...
        'visible','off', ...
        'position',[0.2 0.05 0.6 0.9], ...
        'tag','TimeStampAxes', ...
        'ylim',[TSmin TSmin+ViewRange], ...
        'xlim',[0 1]);
    uicontrol( ...
        'style','slider', ...
        'units','normalized', ...
        'position',[0.8 0.05 0.1 0.9], ...
        'tag','TimeStampSlider', ...
        'min',TSmin, ...
        'max',TSmax, ...
        'sliderstep',[10000/(TSmax-TSmin) 1000000/(TSmax-TSmin)], ...
        'value',TSmin+ViewRange*0.5, ...
        'userdata',NEV, ...
        'callback','NLX_viewEvents(get(gco,''userdata''),get(gco,''value''));');
else
    set(findobj('tag','TimeStampAxes'),'ylim',[TimeValue-0.5*ViewRange TimeValue+0.5*ViewRange]);
end

axes(findobj('tag','TimeStampAxes'));
ylim = get(gca,'ylim');
[TimeStamps,Index,NEV] = NLX_findEvents(NEV,'TIMEWINDOW',ylim);
Index = find(Index);
cla;
for i = 1:length(Index)
    text(-0.01,NEV.TimeStamps(Index(i)),sprintf('%13.0f',NEV.TimeStamps(Index(i))),'verticalalignment','middle','horizontalalignment','right','fontsize',8);
    text(0.01,NEV.TimeStamps(Index(i)),sprintf('%4.0f',NEV.TTL(Index(i))),'verticalalignment','middle','horizontalalignment','left','fontsize',8);
    text(0.2,NEV.TimeStamps(Index(i)),NEV.Eventstring{Index(i)},'verticalalignment','middle','horizontalalignment','left','fontsize',8);
end
    
