function NLX_viewEvents2(NEV)

EvNr = find(NEV.TTL~=0|NEV.EventID==4);
nEv = length(EvNr);

s = cell(nEv,1);
for i=1:nEv
    s{i,1} = sprintf('%5.0f %12.0f %1.0f %5.0f %s',EvNr(i),NEV.TimeStamps(EvNr(i)),NEV.EventID(EvNr(i)),NEV.TTL(EvNr(i)),NEV.Eventstring{EvNr(i)});
end

figure
uicontrol( ...
    'fontname','courier', ...
    'tag','NLX_viewEvents2', ...
    'style','listbox', ...
    'units','normalized', ...
    'position',[0.1 0.1 0.6 0.8], ...
    'string',s, ...
    'min',1, ...
    'max',length(s));
axes( ...
    'units','normalized', ...
    'position',[0.7 0.1 0.1 0.8])

