Description of NLX_DeleteNSE
Home > Neuralynx Tools > NLX_DeleteNSE.m
NLX_DeleteNSE
PURPOSE
Deletes entries from a NSE structure
SYNOPSIS
function NSE = NLX_DeleteNSE(NSE,Index)
DESCRIPTION
 Deletes entries from a NSE structure
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
NLX_AdjustThreshold Adjust the recording threshold.
NLX_RemoveCluster Removes a cluster (e.g. previously selected by SpikeSort) from a *.NSE file
NLX_sortNSE Remove duplicate TimeStamps and sorts Timestamps
SOURCE CODE
function NSE = NLX_DeleteNSE(NSE,Index)
% Deletes entries from a NSE structure
if ~isempty(NSE.TimeStamps);
    NSE.TimeStamps(:,Index) = [];
end
if ~isempty(NSE.ScNr);NSE.ScNr(:,Index) = [];end
if ~isempty(NSE.ClusterNr);NSE.ClusterNr(:,Index) = [];end
if ~isempty(NSE.SpikeFeatures);NSE.SpikeFeatures(:,Index) = [];end
if ~isempty(NSE.SpikeWaveForm);NSE.SpikeWaveForm(:,:,Index) = [];end