Description of NLX_SaveNSE
Home > Neuralynx Tools > NLX_SaveNSE.m
NLX_SaveNSE
PURPOSE
Writes data to an *.NSE file
SYNOPSIS
function NSE = NLX_SaveNSE(NSE,AppendToFile,OverwriteFlag)
DESCRIPTION
 Writes data to an *.NSE file
 NSE ............ structure (see NLX_loadNSE.m)
 AppendToFile ... if is not set to 0 or 1, appends to an existing file
CROSS-REFERENCE INFORMATION
This function calls:
NLX_CheckNSE Checks an NSE structure for number of spikes and existing data.
This function is called by:
NLX_AdjustThreshold Adjust the recording threshold.
NLX_ExtractCluster Extracts a cluster (e.g. previously selected by SpikeSort) from a *.NSE file
NLX_MergeNSE Merge two *.nse files. Relabels cluster in case double labeling
NLX_RemoveCluster Removes a cluster (e.g. previously selected by SpikeSort) from a *.NSE file
NLX_SplitNSE Splits a *.NSE file
SOURCE CODE
function NSE = NLX_SaveNSE(NSE,AppendToFile,OverwriteFlag)
% Writes data to an *.NSE file
% NSE ............ structure (see NLX_loadNSE.m)
% AppendToFile ... if is not set to 0 or 1, appends to an existing file
if nargin<3
    OverwriteFlag = 0;
end
if isempty(NSE.Path)
    [filename,pathname] = uiputfile('*.nse','write to *.NSE file');
    if filename==0;return;end
    NSE.Path = fullfile(pathname,filename);
end
if nargin<2 | isempty(AppendToFile)
    AppendToFile = 0;
end
if OverwriteFlag~= 1 & exist(NSE.Path) & AppendToFile==0
%     button = questdlg(['REPLACE ' strrep(strrep(NSE.Path,'_','\_'),'\','\\') ' ???']);
    button = questdlg(['REPLACE ' NSE.Path ' ???']);
    switch upper(button)
        case 'YES'
        case 'NO'
            [filename,pathname] = uiputfile('*.nse','write to *.NSE file');
            if filename==0;return;end
            NSE.Path = fullfile(pathname,filename);
        case 'CANCEL';return;
        otherwise
            return;
    end
end
ExtractionMode = 1; % write all data to file
ExtractionModeArray = 1;
[NumSpikes,FieldArray,FieldCells] = NLX_CheckNSE(NSE);
Mat2NlxSE(NSE.Path,AppendToFile,ExtractionMode,ExtractionModeArray,NumSpikes,[FieldArray 1],FieldCells{:}, NSE.Header);