Description of NLX_ExtractCluster
Home > Neuralynx Tools > NLX_ExtractCluster.m
NLX_ExtractCluster
PURPOSE
Extracts a cluster (e.g. previously selected by SpikeSort) from a *.NSE file
SYNOPSIS
function NSE = NLX_ExtractCluster(NSE,ClusterNr)
DESCRIPTION
 Extracts a cluster (e.g. previously selected by SpikeSort) from a *.NSE file
 NSE ......... structure, see NLX_loadNSE.m
 ClusterNr ... array of cluster nr
CROSS-REFERENCE INFORMATION
This function calls:
NLX_ExtractNSE Extracts entries from a NSE structure
NLX_SaveNSE Writes data to an *.NSE file
NLX_findSpikes Finds spikes with given properties.
This function is called by:
SOURCE CODE
function NSE = NLX_ExtractCluster(NSE,ClusterNr)
% Extracts a cluster (e.g. previously selected by SpikeSort) from a *.NSE file
% NSE ......... structure, see NLX_loadNSE.m
% ClusterNr ... array of cluster nr
[Index,NSE] = NLX_findSpikes(NSE,'CLUSTER',ClusterNr);
if isempty(NSE.Path);return;end
NSE = NLX_ExtractNSE(NSE,Index);
NSE = NLX_SaveNSE(NSE,0);