Description of NLX_CheckNEV
Home > Neuralynx Tools > NLX_CheckNEV.m
NLX_CheckNEV
PURPOSE
Checks an NEV structure for number of Events and existing data.
SYNOPSIS
function [NumEvents,FieldArray,FieldCells] = NLX_CheckNEV(NEV)
DESCRIPTION
 Checks an NEV structure for number of Events and existing data.
 NEV ... structure (see NLX_loadNEV.m)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
NLX_SaveNEV Writes data to an *.NEV file
NLX_SplitNEV Splits a *.NEV file
NLX_findEvents Finds event timestamps in a *.NEV file.
SOURCE CODE
function [NumEvents,FieldArray,FieldCells] = NLX_CheckNEV(NEV)
% Checks an NEV structure for number of Events and existing data.
%
% NEV ... structure (see NLX_loadNEV.m)
FieldCells = {};
FieldArray = ~[ isempty(NEV.TimeStamps) isempty(NEV.EventID) isempty(NEV.TTL) isempty(NEV.Extras) isempty(NEV.Eventstring) ];
NumEvents = [ size(NEV.TimeStamps,2) size(NEV.EventID,2) size(NEV.TTL,2) size(NEV.Extras,2) size(NEV.Eventstring,1)];
NumEvents = unique(NumEvents(FieldArray));
if length(NumEvents)>1
    error('All field must have same number of spikes!');
end
if nargout==3
    if FieldArray(1);FieldCells = cat(2,FieldCells,{NEV.TimeStamps});end
    if FieldArray(2);FieldCells = cat(2,FieldCells,{NEV.EventID});end
    if FieldArray(3);FieldCells = cat(2,FieldCells,{NEV.TTL});end
    if FieldArray(4);FieldCells = cat(2,FieldCells,{NEV.Extras});end
    if FieldArray(5);FieldCells = cat(2,FieldCells,{NEV.Eventstring});end
end