Description of NLX_findSpikes
Home > Neuralynx Tools > NLX_findSpikes.m
NLX_findSpikes
PURPOSE
Finds spikes with given properties.
SYNOPSIS
function [Index,NSE] = NLX_findSpikes(NSE,varargin)
DESCRIPTION
 Finds spikes with given properties.
 INPUT
 NSE ............. structure containing NSE data, loads file if empty
 Property/Value pairs
 'WAVEFORM' ......  [n X 3] matrix, [sample nr , lower boundary , upper boundery]
                    Boundaries are values between -2047 2047(-32768 32768)
                    Max. in SpiikeSort Template Window (ncf cluster file)
 'CLUSTER' ........ [n]
 'TIME' ........... [lower upper] window, multiple windows in rows
CROSS-REFERENCE INFORMATION
This function calls:
NLX_CheckNSE Checks an NSE structure for number of spikes and existing data.
NLX_LoadNSE Loads a *.nse file into a matlab structure.
This function is called by:
NLX_AdjustThreshold Adjust the recording threshold.
NLX_ExtractCluster Extracts a cluster (e.g. previously selected by SpikeSort) from a *.NSE file
NLX_RemoveCluster Removes a cluster (e.g. previously selected by SpikeSort) from a *.NSE file
NLX_WaveformHist Plots histogram of waveform values at given sample nr.
SOURCE CODE
function [Index,NSE] = NLX_findSpikes(NSE,varargin)
% Finds spikes with given properties.
%
% INPUT
% NSE ............. structure containing NSE data, loads file if empty
% Property/Value pairs
% 'WAVEFORM' ......  [n X 3] matrix, [sample nr , lower boundary , upper boundery]
%                    Boundaries are values between -2047 2047(-32768 32768)
%                    Max. in SpiikeSort Template Window (ncf cluster file)
% 'CLUSTER' ........ [n]
% 'TIME' ........... [lower upper] window, multiple windows in rows
if isempty(NSE)
    NSE = NLX_LoadNSE([],'FULL',1,[],1);
    if isempty(NSE.Path);return;end
end
[NumSpikes,FieldArray] = NLX_CheckNSE(NSE);
Index = logical(zeros(1,NumSpikes));
for i = 1:2:length(varargin)
    switch upper(varargin{i})
        case 'WAVEFORM'
            for j = 1:size(varargin{i+1},1)
                Index(NSE.SpikeWaveForm(varargin{i+1}(j,1),:,:)>=varargin{i+1}(j,2) & NSE.SpikeWaveForm(varargin{i+1}(j,1),:,:)<=varargin{i+1}(j,3)) = 1;
            end
        case 'CLUSTER'
            for j = 1:length(varargin{i+1})
                Index(NSE.ClusterNr(1,:)==varargin{i+1}(j)) = 1;
            end
        case 'TIME'
            for j = 1:size(varargin{i+1},1)
                Index(NSE.TimeStamps(1,:)>=varargin{i+1}(j,1) & NSE.TimeStamps(1,:)<=varargin{i+1}(j,2)) = 1;
            end
        otherwise
            error('Don''t know what to look for!');
    end
end