Description of NLX_AdjustThreshold
Home > Neuralynx Tools > NLX_AdjustThreshold.m
NLX_AdjustThreshold
PURPOSE
Adjust the recording threshold.
SYNOPSIS
function NSE = NLX_AdjustThreshold(NSE,NewThresholdValue,WaveFormAlign,SaveFlag)
DESCRIPTION
 Adjust the recording threshold.
 NSE ................. structure, see NLX_loadNSE.m
 NewThresholdValue ... Boundaries are values between -2047 2047(-32768 32768)
 WaveFormAlign ....... Sample nr waveform alignment. Default is 8
CROSS-REFERENCE INFORMATION
This function calls:
NLX_DeleteNSE Deletes entries from a NSE structure
NLX_SaveNSE Writes data to an *.NSE file
NLX_findSpikes Finds spikes with given properties.
This function is called by:
SOURCE CODE
function NSE = NLX_AdjustThreshold(NSE,NewThresholdValue,WaveFormAlign,SaveFlag)
% Adjust the recording threshold.
% NSE ................. structure, see NLX_loadNSE.m
% NewThresholdValue ... Boundaries are values between -2047 2047(-32768 32768)
% WaveFormAlign ....... Sample nr waveform alignment. Default is 8
if nargin<3
    WaveFormAlign = 8;
if nargin<4
    SaveFlag=1;
end;end
if NewThresholdValue<0
    [Index,NSE] = NLX_findSpikes(NSE,'WAVEFORM',[WaveFormAlign -2047 NewThresholdValue]);
else
    [Index,NSE] = NLX_findSpikes(NSE,'WAVEFORM',[WaveFormAlign NewThresholdValue 2047]);
end
if isempty(NSE.Path);return;end
NSE = NLX_DeleteNSE(NSE,~Index);% delete all waveforms not in window
if SaveFlag==1
    NSE = NLX_SaveNSE(NSE,0);
end