Description of NLX_ExtractNEV
Home > Neuralynx Tools > NLX_ExtractNEV.m
NLX_ExtractNEV
PURPOSE
Extracts entries from a NEV structure
SYNOPSIS
function NEV = NLX_ExtractNEV(NEV,Index)
DESCRIPTION
 Extracts entries from a NEV structure
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
NLX_ReadTrialsFromNEV reads trial events according to events defined in settings structure
NLX_SplitNEV Splits a *.NEV file
NLX_getEventType extract digital/user committed events
SOURCE CODE
function NEV = NLX_ExtractNEV(NEV,Index)
% Extracts entries from a NEV structure
if ~isempty(NEV.TimeStamps);NEV.TimeStamps=NEV.TimeStamps(:,Index);end
if ~isempty(NEV.EventID);NEV.EventID=NEV.EventID(:,Index);end
if ~isempty(NEV.TTL);NEV.TTL=NEV.TTL(:,Index);end
if ~isempty(NEV.Extras);NEV.Extras=NEV.Extras(:,Index);end
if ~isempty(NEV.Eventstring);NEV.Eventstring=NEV.Eventstring(Index,:);end