Description of NLX_WaveformHist
Home > Neuralynx Tools > NLX_WaveformHist.m
NLX_WaveformHist
PURPOSE
Plots histogram of waveform values at given sample nr.
SYNOPSIS
function NSE = NLX_WaveformHist(NSE,ClusterNr,SampleNr)
DESCRIPTION
 Plots histogram of waveform values at given sample nr.
CROSS-REFERENCE INFORMATION
This function calls:
NLX_ClusterColor Coloring for cell clusters
NLX_LoadNSE Loads a *.nse file into a matlab structure.
NLX_findSpikes Finds spikes with given properties.
This function is called by:
SOURCE CODE
function NSE = NLX_WaveformHist(NSE,ClusterNr,SampleNr)
% Plots histogram of waveform values at given sample nr.
NumClust = length(ClusterNr);
NumSamp = length(SampleNr);
if isempty(NSE)
    NSE = NLX_LoadNSE([],'WAVEFORMS',1,[]);
end
figure('color','k');
for i=1:NumClust
    for j=1:NumSamp
        subplot(NumSamp,NumClust,(j-1)*NumClust+i)
        Index = NLX_findSpikes(NSE,'CLUSTER',ClusterNr(i));
        Bins = [-2047:2047/15:0 2047/15:2047/15:2047];
        N = hist(NSE.SpikeWaveForm(SampleNr(j),1,Index),Bins);
        h = bar(Bins,N);
        set(h,'edgecolor','none','facecolor',NLX_ClusterColor(i));
        set(gca,'color','k', ...
            'xcolor',[.5 .5 .5], 'xtick',[-2000:100:2000], ...
            'ycolor',[.5 .5 .5])
    end
end